### PR TITLE
Dev

### PR DESCRIPTION
**Pull request by Xolanisyav04**
This is our combined work guys the whole Movie Search database, built with react, using the OMDB api to get movies and display them with their information, also able to add a movie to favourites.

### CODE REVIEW

**Review by asandan8106 — CHANGES_REQUESTED** [review]
Nice work guys ,this looks good. I think it would be even more nicer if I added an intro page, what do you think?

**Review by Pali-Pali — APPROVED** [review]
Yes you can add an intro page plus it will make the website to look nicer

**Comment by RolivhuwaMuzila** [comment]
> Nice work guys ,this looks good. I think it would be even more nicer if I added an intro page, what do you think?

Yes that's a good idea you can work on it

**Review by asandan8106 — CHANGES_REQUESTED** [review]
The website looks good with the intro included

**Review by RolivhuwaMuzila — APPROVED** [review]
You can merge it is fine

**Review by asandan8106 — APPROVED** [review]

**Pull request merged**
